binary_sensor:
  - platform: inv_8851
    bus_and_grid_voltage_match:
      name: "Bus and grid voltage match"

sensor:
  - platform: inv_8851
    grid_current:
      name: "Grid current"
      id: grid_current
    grid_frequency:
      name: "Grid frequency"
    grid_voltage:
      name: "Grid voltage"
      id: grid_voltage

  - platform: template
    name: "Grid power"
    id: grid_power
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    accuracy_decimals: 1
    lambda: |-
      if (!id(grid_voltage).has_state() || id(grid_voltage).state < 50.0) {
        return 0.0;
      }
      float load = id(load_power).has_state() ? id(load_power).state : 0.0;
      float pv = id(pv_power).has_state() ? id(pv_power).state : 0.0;
      float battery = id(battery_power).has_state() ? id(battery_power).state : 0.0;
      float grid_balance = load - pv + battery;
      float native_grid = id(grid_voltage).state * (id(grid_current).has_state() ? id(grid_current).state : 0.0);
      
      float final_grid = std::max(grid_balance, native_grid);
      return final_grid > 0 ? final_grid : 0.0;

  - platform: integration
    name: "Grid Energy Total"
    sensor: grid_power
    time_unit: h
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    integration_method: left
    filters:
      - multiply: 0.001
    unit_of_measurement: "kWh"

select:
  - platform: inv_8851
    grid_voltage_range:
      name: "Grid voltage range"
    on_grid:
      name: "On grid"
    power_buzzer:
      name: "Power buzzer"
